namespace OpenDota.NET.Players
{
    public enum HistogramField
    {
        Kills,
        ActionsPerMinute,
        Assists,
        Comeback,
        CourierKills,
        Deaths,
        Denies,
        Duration,
        EFFAt10,
        GemsPurchased,
        GoldPerMinute,
        HeroDamage,
        HeroHealing,
        KDA,
        LastHits,
        Level,
        Loss,
        MapPings,
        NeutralKills,
        ObserversPurchased,
        RapiersPurchased,
        SentriesPurchased,
        Stomp,
        Stuns,
        Throw,
        TowerDamage,
        TowerKills,
        TPsPurchased,
        XPPerMinute
    }
}